apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    # Reference to created 
    # by Docker Pods.
    # See the container label below.
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: igorya5v/react-client
          ports:
            - containerPort: 3000