apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    # Reference to created 
    # by Docker Pods.
    # See the container label below.
    matchLabels:
      any_tag: worker
  template:
    metadata:
      labels:
        any_tag: worker
    spec:
      containers:
        - name: worker
          image: igorya5v/worker
          # Environment variables
          env: 
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'